### PR TITLE
First draft for MinIO app

### PR DESCRIPTION
**Pull request by Limezy**
## PR TODO

- [x] Add licence
- [x] Make the version match the official Ynh format
- [x] Use ynh_string_random
- [ ] Calibrate weights and remove --time argument from progression
- [x] Add a badge with app level in the readme
- [x] Restore, upgrade, backup
- [ ] Change url

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
If that's OK with you @Limezy, if the code and our tests are OK, we will squash all your commits into one.

**Comment by Limezy** [comment]
Sure, feel free !

**Comment by Limezy** [comment]
> 😜 [Test Badge](https://ci-apps-dev.yunohost.org/ci/job/3698)

Ouch, I still have a lot of work !

**Comment by tituspijean** [comment]
Haha indeed. :) Do not hesitate asking for help. ;)
I have invited you to have maintainership of the repo, so that you can invoke the CI like I did. 😉

**Comment by Limezy** [comment]
Invitation seen and accepted. That’s great, thanks !
If I need help, what’s the best channel to help ? Here or on the Forum ?

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
Seems like the bot is sleeping @tituspijean 🤣 @yunohost-bot !

**Comment by tituspijean** [comment]
I forgot to invite you to the organization. 🥲

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
Thanks @tituspijean I can now give orders to the bot 💪

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
> Do not hesitate asking for help. ;)

Hi @tituspijean, since you asked ! I need help for the issue https://github.com/YunoHost-Apps/minio_ynh/issues/2

It seems to be out of my Nginx competence. 
I have a feeling that it's a kind of general Nginx configuration (not standard) that prevents the internal redirect from server to console. My current Nginx conf is very similar to the "official" one found here : https://docs.min.io/docs/setup-nginx-proxy-with-minio.html

**Pull request merged**
