### PR TITLE
Path

### PR DESCRIPTION
**Pull request by ericgaspar**
- Fix `--keep` option with relative path

### CODE REVIEW

**Comment by Limezy** [comment]
Hi @ericgaspar many thanks for your PR !
May I know what you are trying to achieve here ?
Just a bit of cleaning, or is there a real impact on keeping --keep with a relative path ?

**Comment by tituspijean** [comment]
We had a discussion with @alexAubin recently where he *shockingly* revealed that the path for `--keep` is supposed to be relative to the destination directory. Eric is fixing that. 😉

**Comment by Limezy** [comment]
Oh I see ! 
Thanks for the explanation and help. I'll merge.

**Comment by Limezy** [comment]
!testme

**Review by Limezy — APPROVED** [review]

**Pull request merged**
