### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by Limezy** [comment]
I have built that MinIO app only because it was a requirement to run my other Outline app.
Now that Outline can run without MinIO, I'm not interested into spending time on it.
* Do you know any other use of MinIO among Yunohost users ?
* If yes I would like to find another maintainer to take over as I'm having less time than before
* If not, I guess we could stop putting energy on that app !

**Comment by Tagadda** [comment]
Hi, thanks for your time maintaining this package! It was great :D
- Yes, Minio can be used as a S3 object storage provider for many other apps (Mastodon comes to my mind, but there's many more!)
- I can assist on this package but would not requite the maintainer title
- Whenever you want, you just have to remove your name from the `manifest.toml`

**Comment by lapineige** [comment]
All good, let's merge ? :thinking:

**Comment by Tagadda** [comment]
!testme

**Review by Tagadda — APPROVED** [review]

**Comment by lapineige** [comment]
Great thanks @Tagadda !

**Pull request merged**
