### PR TITLE
Apply last example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Not working*

## Solution

- *[Apply last example_ynh](https://github.com/YunoHost-Apps/minio_ynh/commit/d2ee2b9075a8203bdb58b6534e7c6c11510850e1)*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by Limezy** [comment]
Hi @yalh76 many thanks for your kind help on the app !
For your information we have been working in parallel... 
I've finally managed to find a way to have both the minio server and minio console on the same URL.
Please refer to my PR #10 
I will probably merge my nginx.conf change on your PR once it's validated.

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
Hi @yalh76 I'm a little bit lost here : how can we move on to a level higher than 4 ? All tests seem to pass correctly now !
Shall I make a PR to the apps catalog to change Minio state to "working" instead of "in progress" ?

**Comment by yalh76** [comment]
> Hi @yalh76 I'm a little bit lost here : how can we move on to a level higher than 4 ? All tests seem to pass correctly now ! Shall I make a PR to the apps catalog to change Minio state to "working" instead of "in progress" ?

You you have to do a PR on apps.json to make it "working"

**Pull request merged**
